### ISSUE TITLE
Validation missing out on refname in foreach>actions

### ISSUE THREAD

**Issue by brlala** [serverlessworkflow/sdk-java#212]
**What happened**:
Validation passed
**What you expected to happen**:
Validation Fail
**How to reproduce it**:
use this yaml for validation
```
id: Test
version: "1.0"
specVersion: "0.7"
name: Test
description: Test
functions:
  - name: Test
states:
  - name: TestingForEach
    type: foreach
    inputCollection: "${ .archives }"
    iterationParam: archive
    outputCollection: "${ .output}"
    actions:
      - functionRef:
          refName: DoesNotExist
    end:
      terminate: true
```
**Anything else we need to know?**:
for type `operation`, the functionRef will be check against the `functions` provided at the top of the file however the validation is missing if the type is `foreach`

**Environment**:
- Specification version used: v0.7
